import { ContentItem, NavItem, CircleWatcher } from "@/types";

export const navItems: NavItem[] = [
  { label: "Home", href: "/", active: true },
  { label: "Películas", href: "/movies" },
  { label: "Series", href: "/series" },
  { label: "Lista", href: "/my-list" },
  { label: "Círculos", href: "/circle" },
];

const sofía: CircleWatcher = { id: "s", name: "Sofía", initials: "S", avatarColor: "#2563eb", avatarImg: "/img/Avatar 2.png" };
const marco: CircleWatcher = { id: "m", name: "Marco", initials: "M", avatarColor: "#7c3aed", avatarImg: "/img/Avatar 1.png" };
const ana: CircleWatcher   = { id: "a", name: "Ana",   initials: "A", avatarColor: "#db2777", avatarImg: "/img/Avatar 3.png" };
const luis: CircleWatcher  = { id: "l", name: "Luis",  initials: "L", avatarColor: "#059669", avatarImg: "/img/Avatar 4.png" };
const val: CircleWatcher   = { id: "v", name: "Val",   initials: "V", avatarColor: "#d97706" };

/* ─── Hero Carousel ────────────────────────────────────────── */
export const heroItems: ContentItem[] = [
  {
    id: "h1",
    title: "Dune",
    subtitle: "PART TWO",
    year: 2024,
    rating: "8.5",
    genres: ["Sci-Fi", "Drama", "Épico"],
    duration: "2h 46m",
    description:
      "Paul Atreides se une a Chani y los Fremen mientras busca venganza contra los conspiradores que destruyeron a su familia.",
    backdropCss:
      "radial-gradient(ellipse 80% 60% at 70% 40%, #0d1f4a 0%, #050c1e 50%, #08090a 100%)",
    backdropImg: "/img/hero-banner.png",
    titleImg: "/img/Dune 2.png",
    posterCss:
      "linear-gradient(160deg, #1a2e6e 0%, #0a1535 60%, #030610 100%)",
    accentColor: "#3b82f6",
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem", "Austin Butler", "Florence Pugh"],
    circleWatchers: [sofía, marco, ana],
    tags: ["Distópico", "Épico", "Sci-fi oscuro", "Visualmente increíble"],
    reactions: [
      { emoji: "🔥", count: 128, label: "Épico!" },
      { emoji: "❤️", count: 87,  label: "Me encanta" },
      { emoji: "🤯", count: 64,  label: "Wow" },
      { emoji: "🍿", count: 42,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "Denis lo hizo de nuevo 🔥" },
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Qué química tienen los dos ✨" },
    ],
  },
  {
    id: "h2",
    title: "Interstellar",
    year: 2014,
    rating: "8.6",
    genres: ["Sci-Fi", "Drama", "Aventura"],
    duration: "2h 49m",
    description:
      "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.",
    backdropCss:
      "radial-gradient(ellipse 80% 60% at 65% 40%, #0a1520 0%, #05080f 50%, #08090a 100%)",
    backdropImg: "/img/interstellar.png",
    titleImg: "/img/interstellar-logo.png",
    posterCss:
      "linear-gradient(160deg, #102035 0%, #06101a 60%, #020508 100%)",
    posterImg: "/img/interstellar.png",
    accentColor: "#60a5fa",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
    circleWatchers: [marco, sofía, luis],
    tags: ["Mind-blowing", "Sci-fi oscuro", "Emotiva", "Plot twist"],
    reactions: [
      { emoji: "🔥", count: 203, label: "Épico!" },
      { emoji: "🤯", count: 176, label: "Wow" },
      { emoji: "❤️", count: 112, label: "Me encanta" },
      { emoji: "🍿", count: 58,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Zimmer lo hizo de nuevo 🎵" },
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "La escena de los mensajes 😭" },
    ],
  },
  {
    id: "h3",
    title: "Blade Runner 2049",
    year: 2017,
    rating: "8.0",
    genres: ["Sci-Fi", "Neo-Noir", "Acción"],
    duration: "2h 44m",
    description:
      "El descubrimiento de un secreto sepultado durante mucho tiempo lleva a un joven blade runner a rastrear al antiguo blade runner Rick Deckard.",
    backdropCss:
      "radial-gradient(ellipse 80% 60% at 60% 50%, #3d1f06 0%, #1a0d03 50%, #08090a 100%)",
    backdropImg: "/img/blade runner.png",
    titleImg: "/img/blade-runner.png",
    posterCss:
      "linear-gradient(160deg, #7c3a0e 0%, #3d1a05 60%, #100602 100%)",
    posterImg: "/img/blade runner.png",
    accentColor: "#f97316",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks", "Robin Wright"],
    circleWatchers: [sofía, val],
    tags: ["Neo-Noir", "Distópico", "Visualmente increíble", "Slow burn"],
    reactions: [
      { emoji: "🔥", count: 94, label: "Épico!" },
      { emoji: "❤️", count: 71, label: "Me encanta" },
      { emoji: "🤯", count: 45, label: "Wow" },
      { emoji: "🍿", count: 29, label: "Qué escena!" },
    ],
    comments: [
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "Cada frame es una obra de arte 🎨" },
      { author: "Val", avatarColor: "#d97706", initials: "V", text: "Hay que verla en pantalla grande para apreciarla de verdad." },
    ],
  },
  {
    id: "h4",
    title: "Donnie Darko",
    year: 2001,
    rating: "8.0",
    genres: ["Misterio", "Sci-Fi", "Drama"],
    duration: "1h 53m",
    description:
      "Un adolescente problemático es acosado por visiones de un hombre con un traje de conejo gigante que lo manipula para cometer crímenes.",
    backdropCss:
      "radial-gradient(ellipse 80% 60% at 65% 45%, #0f0a1a 0%, #05080f 50%, #08090a 100%)",
    backdropImg: "/img/donnie darko.png",
    titleImg: "/img/donnie darko logo.png",
    posterCss:
      "linear-gradient(160deg, #1a0f30 0%, #0a0614 60%, #020205 100%)",
    posterImg: "/img/donnie darko.png",
    accentColor: "#7c3aed",
    director: "Richard Kelly",
    cast: ["Jake Gyllenhaal", "Jena Malone", "Drew Barrymore", "Mary McDonnell", "Patrick Swayze"],
    circleWatchers: [marco, ana, luis],
    tags: ["Cult classic", "Misterio", "Plot twist", "Mind-blowing"],
    reactions: [
      { emoji: "🤯", count: 156, label: "Wow" },
      { emoji: "🔥", count: 89,  label: "Épico!" },
      { emoji: "❤️", count: 67,  label: "Me encanta" },
      { emoji: "🍿", count: 44,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Todavía no entiendo el final 😅" },
      { author: "Ana",   avatarImg: "/img/Avatar 3.png", avatarColor: "#db2777", initials: "A", text: "Frank el conejo 🐰😱" },
    ],
  },
];

/* ─── Continue Watching ─────────────────────────────────────── */
export const continueWatchingItems: ContentItem[] = [
  {
    id: "cw1",
    title: "Interstellar",
    year: 2014,
    rating: "8.6",
    genres: ["Sci-Fi", "Drama", "Aventura"],
    duration: "2h 49m",
    description: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio en un intento de garantizar la supervivencia de la humanidad.",
    backdropCss: "linear-gradient(135deg, #0a1520 0%, #05080f 100%)",
    posterCss: "linear-gradient(160deg, #102035 0%, #06101a 100%)",
    backdropImg: "/img/interstellar-cw.png",
    posterImg: "/img/interstellar-cw.png",
    accentColor: "#60a5fa",
    progress: 65,
  },
  {
    id: "cw2",
    title: "Blade Runner 2049",
    year: 2017,
    rating: "8.0",
    genres: ["Sci-Fi", "Neo-Noir"],
    duration: "2h 44m",
    description: "El descubrimiento de un secreto sepultado durante mucho tiempo lleva a un joven blade runner a rastrear al antiguo blade runner Rick Deckard.",
    backdropCss: "linear-gradient(135deg, #3d1f06 0%, #1a0d03 100%)",
    posterCss: "linear-gradient(160deg, #7c3a0e 0%, #3d1a05 100%)",
    backdropImg: "/img/bladerunner-cw.png",
    posterImg: "/img/bladerunner-cw.png",
    accentColor: "#f97316",
    progress: 42,
  },
  {
    id: "cw3",
    title: "Donnie Darko",
    year: 2001,
    rating: "8.0",
    genres: ["Misterio", "Sci-Fi"],
    duration: "1h 53m",
    description: "Un adolescente problemático es acosado por visiones de un hombre con un traje de conejo gigante que lo manipula para cometer crímenes.",
    backdropCss: "linear-gradient(135deg, #0f0a1a 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #1a0c2e 0%, #0a0614 100%)",
    backdropImg: "/img/donniedarko-cw.png",
    posterImg: "/img/donniedarko-cw.png",
    accentColor: "#7c3aed",
    progress: 18,
  },
  {
    id: "cw4",
    title: "From",
    year: 2022,
    rating: "7.7",
    genres: ["Terror", "Misterio", "Drama"],
    duration: "1h",
    description: "Una ciudad desconcertante en el corazón de América atrapa a todos los que entran. Los residentes luchan por mantener la civilización.",
    backdropCss: "linear-gradient(135deg, #1a0a06 0%, #2d1208 100%)",
    posterCss: "linear-gradient(160deg, #2d1208 0%, #1a0904 100%)",
    backdropImg: "/img/from-cw.png",
    posterImg: "/img/from-cw.png",
    accentColor: "#ef4444",
    progress: 55,
  },
  {
    id: "cw5",
    title: "Commando",
    year: 1985,
    rating: "6.7",
    genres: ["Acción", "Thriller"],
    duration: "1h 30m",
    description: "Un ex-soldado de élite persigue a quienes secuestraron a su hija para forzarlo a asesinar a un líder latinoamericano.",
    backdropCss: "linear-gradient(135deg, #1a1208 0%, #2d2010 100%)",
    posterCss: "linear-gradient(160deg, #3d2810 0%, #1a1004 100%)",
    backdropImg: "/img/commando-cw.png",
    posterImg: "/img/commando-cw.png",
    accentColor: "#d97706",
    progress: 30,
  },
];

/* ─── Recommended by Circle ─────────────────────────────────── */
export const recommendedItems: ContentItem[] = [
  {
    id: "r1",
    title: "Interstellar",
    year: 2014,
    rating: "8.6",
    genres: ["Sci-Fi", "Drama"],
    duration: "2h 49m",
    description: "Un equipo de exploradores viaja a través de un agujero de gusano en el espacio.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0a1520 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #102035 0%, #06101a 100%)",
    posterImg: "/img/rec-1.png",
    accentColor: "#60a5fa",
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine", "Matt Damon"],
    circleWatchers: [sofía, marco, ana, luis],
    circleCount: "3 la están viendo",
    comment: "La escena del agujero negro te deja sin palabras 🤯",
    tags: ["Mind-blowing", "Sci-fi oscuro", "Emotiva", "Plot twist"],
    reactions: [
      { emoji: "🔥", count: 203, label: "Épico!" },
      { emoji: "🤯", count: 176, label: "Wow" },
      { emoji: "❤️", count: 112, label: "Me encanta" },
      { emoji: "🍿", count: 58,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Zimmer lo hizo de nuevo 🎵" },
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "La escena de los mensajes 😭" },
    ],
  },
  {
    id: "r2",
    title: "Blade Runner 2049",
    year: 2017,
    rating: "8.0",
    genres: ["Sci-Fi", "Neo-Noir"],
    duration: "2h 44m",
    description: "Un joven blade runner descubre un secreto que lo lleva a rastrear al legendario Rick Deckard.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #3d1f06 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #7c3a0e 0%, #3d1a05 100%)",
    posterImg: "/img/rec-2.png",
    accentColor: "#f97316",
    director: "Denis Villeneuve",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas", "Sylvia Hoeks", "Robin Wright"],
    circleWatchers: [marco, val],
    circleCount: "Popular en tu círculo",
    comment: "El ambiente visual es brutal, parece una pintura 🎨",
    tags: ["Neo-Noir", "Distópico", "Visualmente increíble", "Slow burn"],
    reactions: [
      { emoji: "🔥", count: 94, label: "Épico!" },
      { emoji: "❤️", count: 71, label: "Me encanta" },
      { emoji: "🤯", count: 45, label: "Wow" },
      { emoji: "🍿", count: 29, label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Cada frame es una obra de arte 🎨" },
      { author: "Val", avatarColor: "#d97706", initials: "V", text: "Hay que verla en pantalla grande para apreciarla de verdad." },
    ],
  },
  {
    id: "r3",
    title: "Donnie Darko",
    year: 2001,
    rating: "8.0",
    genres: ["Misterio", "Sci-Fi"],
    duration: "1h 53m",
    description: "Un adolescente problemático es acosado por visiones de un hombre con un traje de conejo gigante.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0f0a1a 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #1a0f30 0%, #0a0614 100%)",
    posterImg: "/img/rec-3.png",
    accentColor: "#7c3aed",
    director: "Richard Kelly",
    cast: ["Jake Gyllenhaal", "Jena Malone", "Drew Barrymore", "Mary McDonnell", "Patrick Swayze"],
    circleWatchers: [ana, sofía],
    circleCount: "2 ya la terminaron",
    comment: "El final te deja pensando días 🐇",
    tags: ["Cult classic", "Misterio", "Plot twist", "Mind-blowing"],
    reactions: [
      { emoji: "🤯", count: 156, label: "Wow" },
      { emoji: "🔥", count: 89,  label: "Épico!" },
      { emoji: "❤️", count: 67,  label: "Me encanta" },
      { emoji: "🍿", count: 44,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Todavía no entiendo el final 😅" },
      { author: "Ana",   avatarImg: "/img/Avatar 3.png", avatarColor: "#db2777", initials: "A", text: "Frank el conejo 🐰😱" },
    ],
  },
  {
    id: "r4",
    title: "From",
    year: 2022,
    rating: "7.7",
    genres: ["Terror", "Misterio"],
    duration: "1h",
    description: "Una ciudad desconcertante en el corazón de América atrapa a todos los que entran.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #1a0a06 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #2d1208 0%, #1a0904 100%)",
    posterImg: "/img/rec-4.png",
    accentColor: "#ef4444",
    director: "John Griffin",
    cast: ["Harold Perrineau", "Catalina Sandino Moreno", "Eion Bailey", "Hannah Cheramy"],
    circleWatchers: [marco, luis],
    circleCount: "Carla la recomienda",
    comment: "No puedo parar de verla, cada capítulo es mejor",
    tags: ["Terror", "Adictiva", "Misterio", "Cliffhanger"],
    reactions: [
      { emoji: "🔥", count: 118, label: "Épico!" },
      { emoji: "🤯", count: 93,  label: "Wow" },
      { emoji: "❤️", count: 52,  label: "Me encanta" },
      { emoji: "🍿", count: 67,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Cada capítulo mejor que el anterior 🔥" },
      { author: "Luis",  avatarImg: "/img/Avatar 4.png", avatarColor: "#059669",  initials: "L", text: "Te engancha desde el primer ep ✨" },
    ],
  },
  {
    id: "r5",
    title: "Commando",
    year: 1985,
    rating: "6.7",
    genres: ["Acción", "Thriller"],
    duration: "1h 30m",
    description: "Un ex-soldado de élite persigue a quienes secuestraron a su hija.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #1a1208 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #3d2810 0%, #1a1004 100%)",
    posterImg: "/img/rec-5.png",
    accentColor: "#d97706",
    director: "Mark L. Lester",
    cast: ["Arnold Schwarzenegger", "Rae Dawn Chong", "Dan Hedaya", "Vernon Wells"],
    circleWatchers: [val, sofía, luis],
    circleCount: "Ricardo ya la terminó",
    comment: "Clásico de los 80 que nunca falla 💪",
    tags: ["Acción", "Clásico 80s", "Entretenida"],
    reactions: [
      { emoji: "🔥", count: 74, label: "Épico!" },
      { emoji: "❤️", count: 58, label: "Me encanta" },
      { emoji: "🍿", count: 41, label: "Qué escena!" },
      { emoji: "🤯", count: 12, label: "Wow" },
    ],
    comments: [
      { author: "Val",   avatarColor: "#d97706", initials: "V", text: "Schwarzenegger en su mejor momento. Pura nostalgia." },
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "Los one-liners son legendarios jajaja nunca falla." },
    ],
  },
  {
    id: "r6",
    title: "Penny Dreadful",
    year: 2014,
    rating: "8.2",
    genres: ["Drama", "Terror", "Fantasía"],
    duration: "1h",
    description: "Explora los mitos de terror más oscuros del siglo XIX en la ciudad victoriana de Londres.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #1a0812 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #3d0a20 0%, #1a040e 60%, #080408 100%)",
    posterImg: "/img/top-series-5.png",
    accentColor: "#dc2626",
    director: "John Logan",
    cast: ["Eva Green", "Josh Hartnett", "Timothy Dalton", "Billie Piper", "Reeve Carney"],
    circleWatchers: [sofía, ana],
    circleCount: "2 ya la terminaron",
    comment: "Eva Green es absolutamente escalofriante 🖤",
    tags: ["Gótico", "Terror", "Victoriano", "Oscuro"],
    reactions: [
      { emoji: "🔥", count: 142, label: "Épico!" },
      { emoji: "❤️", count: 98,  label: "Me encanta" },
      { emoji: "🤯", count: 76,  label: "Wow" },
      { emoji: "🍿", count: 31,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "Eva Green se roba cada escena. Impresionante." },
      { author: "Ana",   avatarImg: "/img/Avatar 3.png", avatarColor: "#db2777", initials: "A", text: "La atmósfera gótica es perfecta 🖤" },
    ],
  },
  {
    id: "r7",
    title: "The 4400",
    year: 2004,
    rating: "7.5",
    genres: ["Sci-Fi", "Drama", "Misterio"],
    duration: "1h",
    description: "4.400 personas desaparecidas regresan de golpe sin haber envejecido, algunas con habilidades inexplicables.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0a1020 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #0d1a3d 0%, #050c1e 60%, #020408 100%)",
    posterImg: "/img/top-series-3.png",
    accentColor: "#3b82f6",
    director: "Scott Peters",
    cast: ["Joel Gretsch", "Jacqueline McKenzie", "Billy Campbell", "Mahershala Ali"],
    circleWatchers: [marco, luis, val],
    circleCount: "3 la están viendo",
    comment: "La premisa es fascinante, no la conocía ✨",
    tags: ["Sci-Fi", "Misterio", "Sobrenatural", "Underrated"],
    reactions: [
      { emoji: "🤯", count: 88,  label: "Wow" },
      { emoji: "🔥", count: 67,  label: "Épico!" },
      { emoji: "❤️", count: 54,  label: "Me encanta" },
      { emoji: "🍿", count: 39,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Casi nadie la conoce, tremenda serie." },
      { author: "Luis",  avatarImg: "/img/Avatar 4.png", avatarColor: "#059669",  initials: "L", text: "Mahershala Ali en sus inicios 🙌" },
    ],
  },
  {
    id: "r8",
    title: "Spider-Man: Sin Camino a Casa",
    year: 2021,
    rating: "8.2",
    genres: ["Acción", "Aventura", "Sci-Fi"],
    duration: "2h 28m",
    description: "Con su identidad al descubierto, Peter Parker pide ayuda al Doctor Strange para restaurar su secreto.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0a1830 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #0f2448 0%, #071224 60%, #030810 100%)",
    posterImg: "/img/top-movie-1.png",
    accentColor: "#e11d48",
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch", "Jamie Foxx", "Willem Dafoe"],
    circleWatchers: [sofía, marco, ana, luis, val],
    circleCount: "5 ya la terminaron",
    comment: "El final me dejó con la boca abierta 😱",
    tags: ["Multiverse", "Épico", "Marvel", "Nostálgica"],
    reactions: [
      { emoji: "😱", count: 312, label: "Sorpresa!" },
      { emoji: "🔥", count: 289, label: "Épico!" },
      { emoji: "❤️", count: 201, label: "Me encanta" },
      { emoji: "🤯", count: 178, label: "Wow" },
    ],
    comments: [
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "La escena del portal... no puedo 😭🔥" },
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "La mejor película de superhéroes en años." },
    ],
  },
  {
    id: "r9",
    title: "True Detective",
    year: 2014,
    rating: "9.0",
    genres: ["Drama", "Thriller", "Misterio"],
    duration: "1h",
    description: "Dos detectives de Louisiana persiguen a un asesino en serie a lo largo de diecisiete años.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #1a1406 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #2d2208 0%, #151004 60%, #080604 100%)",
    posterImg: "/img/top-series-7.png",
    accentColor: "#d97706",
    director: "Cary Joji Fukunaga",
    cast: ["Matthew McConaughey", "Woody Harrelson", "Michelle Monaghan", "Michael Potts"],
    circleWatchers: [val, sofía],
    circleCount: "2 ya la terminaron",
    comment: "McConaughey da el mejor monólogo de la televisión 🎭",
    tags: ["Noir", "Filosófico", "Slow burn", "Must watch"],
    reactions: [
      { emoji: "🔥", count: 247, label: "Épico!" },
      { emoji: "🤯", count: 189, label: "Wow" },
      { emoji: "❤️", count: 134, label: "Me encanta" },
      { emoji: "🍿", count: 82,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Val",   avatarColor: "#d97706", initials: "V", text: "Rust Cohle es el personaje más filosófico de la TV." },
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "El final de temporada es magistral 🎭" },
    ],
  },
  {
    id: "r10",
    title: "Noche en el Museo",
    year: 2006,
    rating: "6.4",
    genres: ["Comedia", "Aventura", "Familia"],
    duration: "1h 48m",
    description: "Un guardia de seguridad descubre que los exhibits del Museo de Historia Natural cobran vida cada noche.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #1a1008 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #3d2208 0%, #1e1004 60%, #0a0602 100%)",
    posterImg: "/img/top-movie-3.png",
    accentColor: "#f59e0b",
    director: "Shawn Levy",
    cast: ["Ben Stiller", "Carla Gugino", "Dick Van Dyke", "Bill Cobbs", "Owen Wilson"],
    circleWatchers: [ana, luis],
    circleCount: "Carla la recomienda",
    comment: "Un clásico familiar que nunca se pone viejo 🦖",
    tags: ["Comedia", "Familia", "Divertida", "Clásica"],
    reactions: [
      { emoji: "❤️", count: 163, label: "Me encanta" },
      { emoji: "🍿", count: 121, label: "Qué escena!" },
      { emoji: "🔥", count: 48,  label: "Épico!" },
      { emoji: "🤯", count: 22,  label: "Wow" },
    ],
    comments: [
      { author: "Ana",  avatarImg: "/img/Avatar 3.png", avatarColor: "#db2777", initials: "A", text: "La vi de niña y sigue siendo igual de buena 🦕" },
      { author: "Luis", avatarImg: "/img/Avatar 4.png", avatarColor: "#059669",  initials: "L", text: "El T-Rex persiguiendo el hueso jajaja 😂" },
    ],
  },
  {
    id: "r11",
    title: "La Era del Hielo",
    year: 2002,
    rating: "7.5",
    genres: ["Animación", "Comedia", "Aventura"],
    duration: "1h 21m",
    description: "Un mamut, un perezoso y un tigre dientes de sable se unen para devolver a un bebé humano con su familia.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0a1828 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #0f2c4a 0%, #071520 60%, #030810 100%)",
    posterImg: "/img/top-series-9.png",
    accentColor: "#60a5fa",
    director: "Chris Wedge",
    cast: ["Ray Romano", "John Leguizamo", "Denis Leary", "Goran Visnjic"],
    circleWatchers: [marco, sofía, val],
    circleCount: "3 la recomiendan",
    comment: "Scrat persiguiendo su bellota es la historia más trágica del cine 🐿️",
    tags: ["Animación", "Nostálgica", "Comedia", "Familia"],
    reactions: [
      { emoji: "❤️", count: 198, label: "Me encanta" },
      { emoji: "🍿", count: 145, label: "Qué escena!" },
      { emoji: "🔥", count: 87,  label: "Épico!" },
      { emoji: "🤯", count: 34,  label: "Wow" },
    ],
    comments: [
      { author: "Marco", avatarImg: "/img/Avatar 1.png", avatarColor: "#7c3aed", initials: "M", text: "Generación completa creciendo con esta película 🙌" },
      { author: "Val",   avatarColor: "#d97706", initials: "V", text: "Scrat es el protagonista real, no Manny." },
    ],
  },
  {
    id: "r12",
    title: "Mr. Robot",
    year: 2015,
    rating: "8.7",
    genres: ["Drama", "Thriller", "Sci-Fi"],
    duration: "1h",
    description: "Un joven programador con ansias sociales trabaja como ingeniero de ciberseguridad y también como hacker.",
    backdropCss: "radial-gradient(ellipse 100% 80% at 50% 50%, #0a0a14 0%, #08090a 100%)",
    posterCss: "linear-gradient(160deg, #0d0d20 0%, #060610 60%, #030306 100%)",
    posterImg: "/img/top-series-8.png",
    accentColor: "#e11d48",
    director: "Sam Esmail",
    cast: ["Rami Malek", "Christian Slater", "Portia Doubleday", "Carly Chaikin", "Martin Wallström"],
    circleWatchers: [sofía, marco, luis],
    circleCount: "3 ya la terminaron",
    comment: "La mejor serie sobre hacking que existe. Técnicamente perfecta.",
    tags: ["Hacking", "Psicológico", "Thriller", "Must watch"],
    reactions: [
      { emoji: "🤯", count: 276, label: "Wow" },
      { emoji: "🔥", count: 231, label: "Épico!" },
      { emoji: "❤️", count: 167, label: "Me encanta" },
      { emoji: "🍿", count: 94,  label: "Qué escena!" },
    ],
    comments: [
      { author: "Sofía", avatarImg: "/img/Avatar 2.png", avatarColor: "#2563eb", initials: "S", text: "Rami Malek es absolutamente perfecto en este papel." },
      { author: "Luis",  avatarImg: "/img/Avatar 4.png", avatarColor: "#059669",  initials: "L", text: "El giro de la temporada 1... 🤯" },
    ],
  },
];

/* ─── Sponsored Banner ─────────────────────────────────────── */
export const sponsoredItem: ContentItem = {
  id: "sp1",
  title: "Más historias para compartir",
  year: 2024,
  rating: "",
  genres: ["Paramount+"],
  duration: "",
  description:
    "Al suscribirte obtienes un 15% OFF y accedes a mucho más contenido desde Meli Play.",
  backdropCss:
    "radial-gradient(ellipse 120% 80% at 60% 50%, #003366 0%, #001833 40%, #08090a 100%)",
  posterCss:
    "linear-gradient(160deg, #003d7a 0%, #001e3d 100%)",
  accentColor: "#0066cc",
  sponsored: true,
  sponsorName: "Paramount+",
  circleWatchers: [sofía, marco],
  circleCount: "Ricardo y Sofía vieron",
};

/* ─── Sponsored related cards (3 portrait cards shown to the right) ── */
export const sponsoredRelatedItems: ContentItem[] = [
  {
    id: "sp-r1",
    title: "Un Lugar en Silencio: Día Uno",
    year: 2024,
    rating: "7.1",
    genres: ["Terror", "Sci-Fi"],
    duration: "1h 39m",
    description: "",
    backdropCss: "",
    posterCss: "linear-gradient(160deg, #1a0a06 0%, #0a0402 100%)",
    posterImg: "/img/quiet-place.jpg",
    accentColor: "#ef4444",
  },
  {
    id: "sp-r2",
    title: "Espíritus en la Escuela",
    year: 2023,
    rating: "6.8",
    genres: ["Thriller", "Drama"],
    duration: "1h 52m",
    description: "",
    backdropCss: "",
    posterCss: "linear-gradient(160deg, #0a0e1a 0%, #05070f 100%)",
    posterImg: "/img/espiritus-escuela.jpg",
    accentColor: "#3b82f6",
  },
  {
    id: "sp-r3",
    title: "Dexter: Resurrección",
    year: 2024,
    rating: "7.4",
    genres: ["Crimen", "Thriller"],
    duration: "1h",
    description: "",
    backdropCss: "",
    posterCss: "linear-gradient(160deg, #1a0606 0%, #0a0202 100%)",
    posterImg: "/img/dexter.jpg",
    accentColor: "#dc2626",
  },
];

/* ─── Top 10 Películas ──────────────────────────────────────── */
export const topMovies: ContentItem[] = [
  { id: "tm1",  rank: 1,  title: "Dune: Part Two",       year: 2024, rating: "8.5", genres: ["Sci-Fi", "Épico"],          duration: "2h 46m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #5a3a0a 0%, #2a1a04 100%)", posterImg: "/img/top-movie-1.png",  accentColor: "#f1c036" },
  { id: "tm2",  rank: 2,  title: "Oppenheimer",           year: 2023, rating: "8.3", genres: ["Historia", "Drama"],        duration: "3h 0m",  description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #4a2e0d 0%, #251604 100%)", posterImg: "/img/top-movie-2.png",  accentColor: "#d97706" },
  { id: "tm3",  rank: 3,  title: "Poor Things",           year: 2023, rating: "7.8", genres: ["Fantasía", "Comedia"],      duration: "2h 21m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #5a1470 0%, #280835 100%)", posterImg: "/img/top-movie-3.png",  accentColor: "#a855f7" },
  { id: "tm4",  rank: 4,  title: "Interstellar",          year: 2014, rating: "8.6", genres: ["Sci-Fi", "Drama"],          duration: "2h 49m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #102035 0%, #06101a 100%)", posterImg: "/img/top-movie-4.png",  accentColor: "#60a5fa" },
  { id: "tm5",  rank: 5,  title: "Blade Runner 2049",     year: 2017, rating: "8.0", genres: ["Sci-Fi", "Neo-Noir"],       duration: "2h 44m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #7c3a0e 0%, #3d1a05 100%)", posterImg: "/img/top-movie-5.png",  accentColor: "#f97316" },
  { id: "tm6",  rank: 6,  title: "Donnie Darko",          year: 2001, rating: "8.0", genres: ["Misterio", "Sci-Fi"],       duration: "1h 53m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #1a0f30 0%, #0a0614 100%)", posterImg: "/img/top-movie-6.png",  accentColor: "#7c3aed" },
  { id: "tm7",  rank: 7,  title: "Under the Dome",        year: 2013, rating: "6.9", genres: ["Sci-Fi", "Misterio"],       duration: "1h",     description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #0a1214 0%, #05070a 100%)", posterImg: "/img/top-movie-7.png",  accentColor: "#38bdf8" },
  { id: "tm8",  rank: 8,  title: "Commando",              year: 1985, rating: "6.7", genres: ["Acción", "Thriller"],       duration: "1h 30m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #3d2810 0%, #1a1004 100%)", posterImg: "/img/top-movie-8.png",  accentColor: "#d97706" },
  { id: "tm9",  rank: 9,  title: "From",                  year: 2022, rating: "7.7", genres: ["Terror", "Misterio"],       duration: "1h",     description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #2d1208 0%, #1a0904 100%)", posterImg: "/img/top-movie-9.png",  accentColor: "#ef4444" },
  { id: "tm10", rank: 10, title: "Anatomy of a Fall",     year: 2023, rating: "7.7", genres: ["Drama", "Misterio"],        duration: "2h 32m", description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #1a1208 0%, #08090a 100%)", posterImg: "/img/top-movie-10.png", accentColor: "#6b7280" },
];

/* ─── Top 10 Series ─────────────────────────────────────────── */
export const topSeries: ContentItem[] = [
  { id: "ts1",  rank: 1,  title: "From",                  year: 2022, rating: "7.7", genres: ["Terror", "Misterio"],       duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #2d1208 0%, #1a0904 100%)", posterImg: "/img/top-series-1.png",  accentColor: "#ef4444" },
  { id: "ts2",  rank: 2,  title: "Under the Dome",        year: 2013, rating: "6.9", genres: ["Sci-Fi", "Misterio"],       duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #0a1214 0%, #05070a 100%)", posterImg: "/img/top-series-2.png",  accentColor: "#38bdf8" },
  { id: "ts3",  rank: 3,  title: "Severance",             year: 2022, rating: "8.7", genres: ["Sci-Fi", "Thriller"],       duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #0d1a42 0%, #060e20 100%)", posterImg: "/img/top-series-3.png",  accentColor: "#3b82f6" },
  { id: "ts4",  rank: 4,  title: "Dark",                  year: 2017, rating: "8.7", genres: ["Misterio", "Sci-Fi"],       duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #1a0c2e 0%, #0a0614 100%)", posterImg: "/img/top-series-4.png",  accentColor: "#7c3aed" },
  { id: "ts5",  rank: 5,  title: "House of the Dragon",   year: 2022, rating: "8.4", genres: ["Fantasía", "Drama"],        duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #3a0a0a 0%, #1a0404 100%)", posterImg: "/img/top-series-5.png",  accentColor: "#ef4444" },
  { id: "ts6",  rank: 6,  title: "The Last of Us",        year: 2023, rating: "8.7", genres: ["Drama", "Sci-Fi"],          duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #1a2e0a 0%, #0a1404 100%)", posterImg: "/img/top-series-6.png",  accentColor: "#84cc16" },
  { id: "ts7",  rank: 7,  title: "Succession",            year: 2018, rating: "8.8", genres: ["Drama", "Sátira"],          duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #2d2010 0%, #140e06 100%)", posterImg: "/img/top-series-7.png",  accentColor: "#d97706" },
  { id: "ts8",  rank: 8,  title: "Andor",                 year: 2022, rating: "8.4", genres: ["Sci-Fi", "Thriller"],       duration: "45m",   description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #0a0e1a 0%, #050810 100%)", posterImg: "/img/top-series-8.png",  accentColor: "#6b7280" },
  { id: "ts9",  rank: 9,  title: "The Bear",              year: 2022, rating: "8.7", genres: ["Drama", "Comedia"],         duration: "30m",   description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #3d1a08 0%, #1a0904 100%)", posterImg: "/img/top-series-9.png",  accentColor: "#f97316" },
  { id: "ts10", rank: 10, title: "The White Lotus",       year: 2021, rating: "7.9", genres: ["Drama", "Sátira"],          duration: "1h",    description: "", backdropCss: "", posterCss: "linear-gradient(160deg, #1a140a 0%, #0a0804 100%)", posterImg: "/img/top-series-10.png", accentColor: "#f59e0b" },
];
